from string import ascii_uppercase

from eulerPrimes import get_proper_divisors


class ProjectEuler21to30:
	def problem21(self) -> int:
		# Let d(n) be defined as the sum of proper divisors of n (numbers less
		# than n which divide evenly into n). If d(a) = b and d(b) = a, where
		# a != b, then a and b are an amicable pair and each of a and b are
		# called amicable numbers.For example, the proper divisors of 220 are
		#     1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110;
		# therefore d(220) = 284.
		#     The proper divisors of 284 are 1, 2, 4, 71 and 142;
		#     so d(284) = 220.
		# Evaluate the sum of all the amicable numbers under 10000.
		amicable_nums = set()
		
		for a in range(1, 10001):
			a_divs = get_proper_divisors(a)
			b = sum(a_divs)
			
			if a != b and sum(get_proper_divisors(b)) == a:
				amicable_nums.add(a)
				amicable_nums.add(b)
		return sum(amicable_nums)
	
	def _name_score(self, name: str, charset: str, pos: int) -> int:
		sum = 0
		for ch in name:
			sum += charset.index(ch)
		return (pos + 1) * sum  # 1-indexed
	
	def problem22(self) -> int:
		# Using problem22.txt, a 46K text file containing over five-thousand
		# first names, begin by sorting it into alphabetical order. Then
		# working out the alphabetical value for each name, multiply this value
		# by its alphabetical position in the list to obtain a name score.
		# For example, when the list is sorted into alphabetical order, COLIN,
		# which is worth
		#     3 + 15 + 12 + 9 + 14 = 53
		# is the 938th name in the list. So, COLIN would obtain a score of
		#     938 x 53 = 49714
		# What is the total of all the name scores in the file?
		with open("data/problem22.txt") as file_data:
			data = file_data.read().replace('"', '')
		
		name_list = sorted(data.split(","))
		upr = '0' + ascii_uppercase
		scores = [self._name_score(n, upr, i) for i, n in enumerate(name_list)]
		return sum(scores)

	def problem25(self) -> int:
		# The Fibonacci sequence is defined by the recurrence relation:
		#     F(n) = F(n - 1) + F(n - 2), where F(1) = 1 and F(2) = 1
		# The 12th term, F(12), is the first term to contain three digits. What
		# is the index of the first term in the Fibonacci sequence to contain
		# 1000 digits?
		mem = [0] * 5050
		mem[0] = 1
		mem[1] = 1
		
		for idx in range(2, 5000):
			term = mem[idx - 1] + mem[idx - 2]
			mem[idx] = term
			
			if idx > 4500 and len(str(term)) >= 1000:
				return idx + 1  # mem is 0-indexed
		return 0
	
	def problem29(self) -> int:
		# Consider all integer combinations of a^b for 2<=a<=5 and 2<=b<=5,
		# if they are then placed in numerical order, with any repeats removed,
		# we get the following sequence of 15 distinct terms:
		#     4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
		# How many distinct terms are in the sequence generated by a^b for
		# 2<=a<=100 and 2<=b<=100?
		upper_limit = 100
		solutions = set()
		
		for a in range(2, upper_limit + 1):
			for b in range(2, upper_limit + 1):
				solutions.add(a ** b)
		return len(solutions)

	def problem30(self) -> int:
		# Surprisingly there are only three numbers that can be written as the
		# sum of fourth powers of their digits:
		#     1634, 8208, 9474
		# The sum of these numbers is
		#     1634 + 8208 + 9474 = 19316
		# Find the sum of all the numbers that can be written as the sum of
		# fifth powers of their digits.
		_sum = 0
		for i in range(2, 1000000):
			if i == sum([int(ch) ** 5 for ch in str(i)]):
				_sum += i
		return _sum


if __name__ == "__main__":
	euler = ProjectEuler21to30()
	
	# print(euler.problem22())  # solved
	# print(euler.problem21())  # solved
	# print(euler.problem23())  # TODO unsolved
	# print(euler.problem24())  # TODO unsolved
	print(euler.problem25())  # solved
	# print(euler.problem26())  # TODO unsolved
	# print(euler.problem27())  # TODO unsolved
	# print(euler.problem28())  # TODO unsolved
	# print(euler.problem29())  # solved
	# print(euler.problem30())  # solved
